# Generated by Django 4.2.6 on 2024-07-09 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='vendre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_vente', models.CharField(max_length=20)),
                ('Nom_vendeur', models.CharField(max_length=20)),
                ('KG', models.CharField(max_length=20)),
                ('Prix', models.BigIntegerField()),
                ('date_pub', models.DateTimeField(auto_now_add=True)),
                ('Destination', models.CharField(max_length=20)),
                ('date_voyage', models.DateTimeField()),
            ],
        ),
    ]
