# Generated by Django 4.2.6 on 2024-07-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='vendre',
            new_name='annonces',
        ),
    ]
