# Generated by Django 4.2.6 on 2024-07-10 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0002_rename_vendre_annonces'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonces',
            old_name='Nom_vendeur',
            new_name='numero_vendeur',
        ),
    ]
