# Generated by Django 4.2.6 on 2024-07-11 13:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0004_remove_annonces_code_vente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonces',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
