# Generated by Django 4.2.6 on 2024-07-15 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0006_annonces_titre'),
    ]

    operations = [
        migrations.CreateModel(
            name='compagnie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compagnie', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(default=None, max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='annonces',
            name='titre',
        ),
        migrations.AddField(
            model_name='annonces',
            name='compagnie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Models.compagnie'),
        ),
        migrations.AlterField(
            model_name='annonces',
            name='Destination',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Models.destination'),
        ),
    ]
