# Generated by Django 4.2.6 on 2024-07-16 12:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Models', '0008_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonces',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='annonces',
            name='Destination',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='annonces',
            name='compagnie',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='compagnie',
        ),
        migrations.DeleteModel(
            name='destination',
        ),
    ]
