# Generated by Django 4.2.6 on 2024-07-16 13:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Models', '0010_alter_annonces_kg'),
    ]

    operations = [
        migrations.CreateModel(
            name='annonces_vu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_vu', models.DateTimeField(auto_now_add=True)),
                ('annonces', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Models.annonces')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
