# Generated by Django 4.2.6 on 2024-07-16 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0011_annonces_vu'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonces_vu',
            name='user',
        ),
    ]
