# Generated by Django 4.2.6 on 2024-07-16 14:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Models', '0012_remove_annonces_vu_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='annonces_vu',
            old_name='annonces',
            new_name='annonce',
        ),
        migrations.AddField(
            model_name='annonces_vu',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
