# Generated by Django 4.2.6 on 2024-07-16 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0013_rename_annonces_annonces_vu_annonce_annonces_vu_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonces_vu',
            name='annonce',
        ),
        migrations.RemoveField(
            model_name='annonces_vu',
            name='date_vu',
        ),
        migrations.AddField(
            model_name='annonces_vu',
            name='Destination',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='annonces_vu',
            name='KG',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='annonces_vu',
            name='Prix',
            field=models.BigIntegerField(default=None),
        ),
        migrations.AddField(
            model_name='annonces_vu',
            name='compagnie',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='annonces_vu',
            name='date_pub',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='annonces_vu',
            name='date_voyage',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='annonces_vu',
            name='numero_vendeur',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='annonces',
            name='Destination',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='annonces_vu',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
