# Generated by Django 4.2.6 on 2024-07-16 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0014_remove_annonces_vu_annonce_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonces_vu',
            name='me',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
