# Generated by Django 4.2.6 on 2024-07-16 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0016_remove_annonces_vu_date_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonces_vu',
            name='date_achat',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
