# Generated by Django 4.2.6 on 2024-07-16 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0017_annonces_vu_date_achat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annonces_vu',
            name='date_achat',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
