# Generated by Django 4.2.6 on 2024-07-17 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0020_rename_me_annonces_vu_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birthday',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_images'),
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
