# Generated by Django 4.2.6 on 2024-07-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0024_alter_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='compagnie_aerienne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compagnie', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ville', models.CharField(default=None, max_length=50)),
            ],
        ),
    ]
