# Generated by Django 4.2.6 on 2024-07-21 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0025_compagnie_aerienne_destination'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonces',
            name='vendeur',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='annonces',
            name='Destination',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Models.destination'),
        ),
        migrations.AlterField(
            model_name='annonces',
            name='compagnie',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Models.compagnie_aerienne'),
        ),
    ]
