# Generated by Django 4.2.6 on 2024-07-22 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0027_alter_compagnie_aerienne_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to='Profile'),
        ),
    ]
