# Generated by Django 4.2.6 on 2024-07-25 09:26

import Models.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0028_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonces',
            name='localisation',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='annonces_vu',
            name='localisation',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='annonces',
            name='numero_vendeur',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(upload_to=Models.models.get_upload_path),
        ),
    ]
