# Generated by Django 4.2.6 on 2024-07-25 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0029_annonces_localisation_annonces_vu_localisation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonces_vu',
            name='pseudo',
            field=models.CharField(default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pseudo',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
