# Generated by Django 4.2.6 on 2024-07-25 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0030_annonces_vu_pseudo_alter_profile_pseudo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='annonces_vu',
            name='pseudo',
        ),
        migrations.AlterField(
            model_name='annonces',
            name='localisation',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='annonces',
            name='numero_vendeur',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='annonces_vu',
            name='localisation',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='pseudo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
