# Generated by Django 4.2.6 on 2024-07-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0031_remove_annonces_vu_pseudo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonces',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='annonces_vu',
            name='email',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
