# Generated by Django 4.2.6 on 2024-07-26 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0033_profile_numero_telephone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='numero_telephone',
        ),
    ]
