# Generated by Django 4.2.6 on 2024-07-28 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0034_remove_profile_numero_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonces_vu',
            name='pseudo_vendeur',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
