# Generated by Django 4.2.6 on 2024-08-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Models', '0038_annonces_date_voyage'),
    ]

    operations = [
        migrations.AddField(
            model_name='annonces',
            name='date_pub',
            field=models.DateTimeField(auto_now_add = True),
        ),
    ]
